### ISSUE TITLE
deconsoler deleting unrelated lines at the end of file

### ISSUE THREAD

**Issue by MarkASwanson** [vishysank/console-log-atom#10]
When deconsoling, a number of lines are deleted from the end of the file = the number of console lines removed.

For Example, running deconsole on

``` js
// ...
let foo = 'bar';
console.log('foo', foo);
export default somethingElse;
```

results in:

``` js
// ...
let foo = 'bar';
```

**Comment by vishysank** [comment]
@MarkASwanson thanks for bringing this up, I shall take a look into this and fix.

**Comment by vishysank** [comment]
@MarkASwanson I reworked the deconsole code approach, so I think you shouldn't encounter this issue again. Please do let me know if you still see problems.
