### ISSUE TITLE
"Condition passed" when variable ends with "if" 

### ISSUE THREAD

**Issue by jlucio-key** [vishysank/console-log-atom#11]
Given:

``` javascript
const sif = noiShared.get('sif');
```

Highlight the const `sif` and `ctrl + l`

Produces:

``` javascript
console.log('sif', sif);
const sif = noiShared.ge
console.log('CONDITION PASSED');t('sif');
```

**Comment by vishysank** [comment]
interesting, that is a bug, i shall look to fix it.

**Comment by vishysank** [comment]
@jlucio-key as of v 1.6.3, i believe this bug has been fixed. Please let me know if you see a reoccurence or further issues.

**Comment by miahal7** [comment]
Just updated and it looks good, thanks!
