### ISSUE TITLE
Console-log issues with condition in javascript

### ISSUE THREAD

**Issue by wilsto** [vishysank/console-log-atom#17]
Thanks for this package, very helpfull 
But i can't use it within (not simple) condition.

I explain myself, When we have this 
![image](https://cloud.githubusercontent.com/assets/4889715/19683349/21923abe-9ab2-11e6-9736-7039e7c975a6.png)

we have this unexpected result
![image](https://cloud.githubusercontent.com/assets/4889715/19683357/2fa19da2-9ab2-11e6-8d77-faccf21425d2.png)

do you know where can be the issue ?
Thank you :)

same
![image](https://cloud.githubusercontent.com/assets/4889715/19683435/75f743ce-9ab2-11e6-8ab9-3f59baadd5a9.png)

![image](https://cloud.githubusercontent.com/assets/4889715/19683444/8221dc54-9ab2-11e6-837c-362ffdb1127b.png)

**Comment by vishysank** [comment]
@wilsto thanks for bring this up, I shall take a look at it shortly.

**Comment by vishysank** [comment]
@wilsto , with release v1.65, i believe I have fixed the bug that caused this issue. Please let me know if you still see any issues and I shall re-open this bug. Glad you enjoy using the app, please star if you like it !

**Comment by wilsto** [comment]
It works, thanks @vishysank for the quick fix 👍
