### ISSUE TITLE
deconsoler can't work in a split pane

### ISSUE THREAD

**Issue by zhangDand** [vishysank/console-log-atom#18]
somtimes , the file in the split pane, deconsoler can't find the 'console' line .
 it just log 0 rows have been removed

**Comment by vishysank** [comment]
@zhangDand can you add a gif in here of this behaviour in action so that i can see exactly what the issue is ?

**Comment by vishysank** [comment]
@zhangDand closing this issue due to lack to explanation and follow up. Do open it back up if you have more information.
