### ISSUE TITLE
Add option to disable context menus

### ISSUE THREAD

**Issue by camjackson** [vishysank/console-log-atom#19]
I love the functionality of this plugin, but I only use the keyboard shortcuts. I find that the Right-Click context menus just clutter things up, so I'd like to be able to disable them.

How much work would it be to add an option for this?

**Comment by vishysank** [comment]
@camjackson thats a good suggestion, i'll investigate adding a config option for this.

**Comment by pdonias** [comment]
@vishysank Hi!
I implemented a quick fix for this. If you give me the permissions, I'll push it and create a pull request.

**Comment by vishysank** [comment]
@pdonias that is awesome! Thanks ! I'm not sure how I can give you permissions on atom, but if push a branch to this repo and open a PR, I can review and approve it. When new code is added to master, a new atom version is automatically pushed out.

**Comment by vishysank** [comment]
@pdonias, I'll also add a thank you mention in the documentation, and you'll be included as a contributer on this repo

**Comment by pdonias** [comment]
The problem is I can't seem to be able to push a new branch. (`Permission to vishysank/console-log-atom.git denied to pdonias.`)
But if you go to Settings > Collaborators, you should be able to add me as a collaborator.

**Comment by vishysank** [comment]
@pdonias okay, added you as a collaborator

**Comment by pdonias** [comment]
Thanks :)

**Comment by vishysank** [comment]
@camjackson, as of v 1.8.0 this should now be a config option, thanks to some sweet work by @pdonias. If you guys like using the site, star it on atom or github !

**Comment by camjackson** [comment]
Wow, that was quick!

@pdonias, for future reference, usually people would fork the repo into their own github account, and push it to there. Then you can create a pull request from your fork to the main repo :)

**Comment by pdonias** [comment]
@camjackson copy that, thanks.
