### ISSUE TITLE
Missing semicolons

### ISSUE THREAD

**Issue by joshstar** [vishysank/console-log-atom#2]
I know that semi-colons are not at required by any means in Javascript but it is still far more common to include them rather then to omit them.

Many Javascript apps require building and usually enforce a consistent style guide, not having the semi colon would make the builds fail.

Providing an option to include a semicolon would be the best for both worlds, if its not to complex to implement.

**Comment by wilmoore** [comment]
Perhaps check if selected line has a semicolon and if so, add one, if not, skip it.

**Comment by vishysank** [comment]
this is a good suggestion, thanks for bringing it up. I am so used to coding in Javascript Standard Style that I did not think about this. I will add a package configuration option in an update in a few days.

**Comment by vishysank** [comment]
@Josh-Star and @wilmoore this should now be a configurable options as of v0.6.2. Check it out and let me know if you see any further issues
