### ISSUE TITLE
Formatted JSON.stringify

### ISSUE THREAD

**Issue by deser** [vishysank/console-log-atom#22]
Hi, could you add to `console.log(JSON.stringify(obj))` 2 params to be `console.log(JSON.stringify(obj, null, 2))` ?

Thanks

**Comment by vishysank** [comment]
@deser that is a good idea, I shall go ahead and address this sometime this week and put out an update.

**Comment by deser** [comment]
Hey, any progress here? :)

**Comment by vishysank** [comment]
@deser as of v1.10.0, the json.stringify includes the 2 params null and 2 in order to produce a formatted JSON.Stringify. Star the app on github or atom if you enjoy using it !

**Comment by deser** [comment]
MANY THANKS! :)
