### ISSUE TITLE
Option to retain case?

### ISSUE THREAD

**Issue by Gruntfuggly** [vishysank/console-log-atom#4]
Great idea - I think this will be very useful!

Is there any chance you could add an option to retain the case of the selected item instead of converting to upper?

**Comment by vishysank** [comment]
this is a good suggestion, thanks for bringing it up. I will add a package configuration option in the next update.

enjoy using the package and star it if you like it.

**Comment by vishysank** [comment]
@Gruntfuggly, as of v0.7.0 there is now a package configuration option that retains the case of the identifier of the selected item. It defaults to converting it to caps locks, but if you can now set it to retain the case through the config option. 

Cheers !
