### ISSUE TITLE
Option to always add JSON.stringify

### ISSUE THREAD

**Issue by Gruntfuggly** [vishysank/console-log-atom#6]
Another useful enhancement for me would be to automatically add JSON.stringify, e.g.

`console.log( 'OBJECT', JSON.stringify( object ) );`

I find myself doing it all the time...

**Comment by vishysank** [comment]
@Gruntfuggly that is a good suggestion, I will look into that, might have to set that to a different key mapping. 

I will consider some strategies and add the detail of what the enhancement will be here.

**Comment by vishysank** [comment]
@Gruntfuggly this is now available in v0.8.0 of the package. Thanks for brining this up, and keep adding enhancements of things you want.

Cheers.
