### ISSUE TITLE
I want to run multiple method calls simultaneously

### ISSUE THREAD

**Issue by fuzzygreenblurs** [vishysank/console-log-atom#7]
If I try to add (by highlighting) multiple methods at the same time , it only logs the latest one (see below):

```
// i want to log method1 and method2 at the same time
console.log(method1, method2)   // expected
console.log('METHOD2', method2) // actual
```

**Comment by vishysank** [comment]
in this scenario it would actually be better to separately log each of these in diffferent console.log statements. Let me know if there is a specific reason you might want to run both in one call ?
